version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.82.3

    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8nuser
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - DB_POSTGRESDB_SCHEMA=public
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: always
    networks:
      - n8n_network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=n8nuser
      - POSTGRES_PASSWORD=n8npassword
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - n8n_network

volumes:
  n8n_data:
    name: n8n_data
  postgres_data:
    name: postgres_data

networks:
  n8n_network:
    driver: bridge
